### ISSUE TITLE
build keeps failing

### ISSUE THREAD

**Issue by neonsirenstudios** [notionblog/notion-instagram#22]
i've repeated all the steps from the guide, and every time i try to use the one-click feature for heroku & input all the necessary info, i keep getting these messages:

"App creation failed. Please ensure you have valid values in the above form fields.

There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again."

-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
        !     Push rejected, failed to compile Node.js app. 
        !     Push failed

**Comment by Saulahrys** [comment]
Hi there !
Same problem for me...
``
-----> Installing dependencies
       Installing node modules
       npm ERR! code 1
       npm ERR! path /tmp/build_4bbbc0a0/node_modules/canvas
       npm ERR! command failed
       npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
       npm ERR! Failed to execute '/tmp/build_4bbbc0a0/.heroku/node/bin/node /tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       npm ERR! node-pre-gyp info it worked if it ends with ok
       npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
       npm ERR! node-pre-gyp info using node@18.12.1 | linux | x64
       npm ERR! node-pre-gyp info check checked for "/tmp/build_4bbbc0a0/node_modules/canvas/build/Release/canvas.node" (not found)
       npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz
       npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
       npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.12.1 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
       npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-linux-glibc-x64.tar.gz 
       npm ERR! gyp info it worked if it ends with ok
       npm ERR! gyp info using node-gyp@9.1.0
       npm ERR! gyp info using node@18.12.1 | linux | x64
       npm ERR! gyp info ok 
       npm ERR! gyp info it worked if it ends with ok
       npm ERR! gyp info using node-gyp@9.1.0
       npm ERR! gyp info using node@18.12.1 | linux | x64
       npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
       npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.1/node-v18.12.1-headers.tar.gz
       npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.1/node-v18.12.1-headers.tar.gz
       npm ERR! gyp http GET https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
       npm ERR! gyp http 200 https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
       npm ERR! gyp info spawn /usr/bin/python3
       npm ERR! gyp info spawn args [
       npm ERR! gyp info spawn args   '/tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
       npm ERR! gyp info spawn args   'binding.gyp',
       npm ERR! gyp info spawn args   '-f',
       npm ERR! gyp info spawn args   'make',
       npm ERR! gyp info spawn args   '-I',
       npm ERR! gyp info spawn args   '/tmp/build_4bbbc0a0/node_modules/canvas/build/config.gypi',
       npm ERR! gyp info spawn args   '-I',
       npm ERR! gyp info spawn args   '/tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
       npm ERR! gyp info spawn args   '-I',
       npm ERR! gyp info spawn args   '/app/.cache/node-gyp/18.12.1/include/node/common.gypi',
       npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
       npm ERR! gyp info spawn args   '-Dvisibility=default',
       npm ERR! gyp info spawn args   '-Dnode_root_dir=/app/.cache/node-gyp/18.12.1',
       npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp',
       npm ERR! gyp info spawn args   '-Dnode_lib_file=/app/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
       npm ERR! gyp info spawn args   '-Dmodule_root_dir=/tmp/build_4bbbc0a0/node_modules/canvas',
       npm ERR! gyp info spawn args   '-Dnode_engine=v8',
       npm ERR! gyp info spawn args   '--depth=.',
       npm ERR! gyp info spawn args   '--no-parallel',
       npm ERR! gyp info spawn args   '--generator-output',
       npm ERR! gyp info spawn args   'build',
       npm ERR! gyp info spawn args   '-Goutput_dir=.'
       npm ERR! gyp info spawn args ]
       npm ERR! Package pangocairo was not found in the pkg-config search path.
       npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
       npm ERR! to the PKG_CONFIG_PATH environment variable
       npm ERR! No package 'pangocairo' found
       npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
       npm ERR! gyp ERR! configure error 
       npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
       npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
       npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
       npm ERR! gyp ERR! System Linux 4.4.0-1104-aws
       npm ERR! gyp ERR! command "/tmp/build_4bbbc0a0/.heroku/node/bin/node" "/tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
       npm ERR! gyp ERR! cwd /tmp/build_4bbbc0a0/node_modules/canvas
       npm ERR! gyp ERR! node -v v18.12.1
       npm ERR! gyp ERR! node-gyp -v v9.1.0
       npm ERR! gyp ERR! not ok 
       npm ERR! node-pre-gyp ERR! build error 
       npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_4bbbc0a0/.heroku/node/bin/node /tmp/build_4bbbc0a0/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_4bbbc0a0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_4bbbc0a0/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
       npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
       npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
       npm ERR! node-pre-gyp ERR! System Linux 4.4.0-1104-aws
       npm ERR! node-pre-gyp ERR! command "/tmp/build_4bbbc0a0/.heroku/node/bin/node" "/tmp/build_4bbbc0a0/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       npm ERR! node-pre-gyp ERR! cwd /tmp/build_4bbbc0a0/node_modules/canvas
       npm ERR! node-pre-gyp ERR! node -v v18.12.1
       npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
       npm ERR! node-pre-gyp ERR! not ok
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.7uYpC/_logs/2022-11-17T09_33_04_609Z-debug-0.log
-----> Build failed
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       Some possible problems:
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
      Love,
       Heroku   
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

The promise is tempting, can't wait to try this out :)

**Comment by bboychris168** [comment]
Have you guys found out how to install the app? Ive yet found out how to fix this issue.

**Comment by neonsirenstudios** [comment]
unfortunately i haven't figured it out - will be using other scheduling tools in the meantime

**Comment by bboychris168** [comment]
Ohh ok. You know any goods ones? ive been using paid ones but really dont want to pay for them...

**Comment by neonsirenstudios** [comment]
i believe you can do a lot with social champ for free. that’s one im gonna try 🖤
